name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - arm_pyart
  - eccodes
  pip:
    - cfgrib 
