name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - arm_pyart
  - pip
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - cfgrib
  - eccodes
  - dask
  - distributed
  - jax
  - tensorflow==2.6
  - tensorflow-probability
